site_name: My Docs
nav:
  - Home: index.md
  - Git Basics:
    - What is Git?: git-basics/what-is-git.md
    - Installing Git: git-basics/installing-git.md
    - Common Git Commands: git-basics/common-git-commands.md
    - Configuring Git: git-basics/configuring-git.md
    - Cloning a Repository: git-basics/cloning-a-repository.md
    - Creating a Branch: git-basics/creating-a-branch.md
    - Creating a New Commit: git-basics/creating-a-new-commit.md
    - Changing a Previous Commit's Message: git-basics/changing-a-previous-commit-message.md
    - Opening a Pull Request: git-basics/opening-a-pull-request.md
    - Reverting a Commit: git-basics/reverting-a-commit.md
    - Git Best Practices: git-basics/git-best-practices.md
  - Git Advanced: git-advanced/index.md
  - Using GitHub: using-github/index.md
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
