site_name: My Docs
nav:
  - Home: index.md
  - Git Basics:
    - What is Git?: git-basics/what-is-git.md
    - Installing Git: git-basics/installing-git.md
    - Common Git Commands: git-basics/common-git-commands.md
    - Configuring Git: git-basics/configuring-git.md
    - Basic Git Workflow: git-basics/basic-git-workflow.md
    - Pull Request Merging Guidelines: git-basics/pr-merging-guidelines.md
    - Git Best Practices: git-basics/git-best-practices.md
  - Git Advanced: git-advanced/index.md
  - Using GitHub: using-github/index.md
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
