site_name: IHT Git & GitHub Guide
nav:
  - Table of Contents: index.md
  - Getting Familiar with Git:
    - What is Git?: git-basics/what-is-git.md
    - Installing Git: git-basics/installing-git.md
    - Common Git Commands: git-basics/common-git-commands.md
    - Configuring Git: git-basics/configuring-git.md
    - Basic Git Workflow: git-basics/basic-git-workflow.md
    - Pull Request Merging Guidelines: git-basics/pr-merging-guidelines.md
    - Git Best Practices: git-basics/git-best-practices.md
  - Using GitHub Effectively:
    - GitHub Guides: using-github/index.md
    - GitHub Access Control: using-github/github-access-control.md
    - Creating a Repository: using-github/creating-a-repository.md
    - Creating a Pull Request Template: using-github/creating-a-pull-request-template.md
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
